import { fichePayload } from "./schemas";
import {z} from "zod"

/**
 * Unified type exports.
 * Database types are generated by Prisma from prisma/schema.prisma.
 */
export type {
  ContactRequest,
  Fiche,
  FicheScan,
  Formule,
  Statut,
  User,
  UserRole,
} from "../../server/database/generated/prisma/client";
export * from "../_core/errors";

export type OAuthState = {
  redirectUri: string;
  nonce?: string;
  invitationToken?: string;
};

// Fiche
export type FichePayload = z.infer<typeof fichePayload>;
